name: CI-CD pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests

    - name: Build image
      run: cp -R docker target/ && cp target/*.jar docker/
      
    - name: Docker login
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
         
    - name: Build Container image
      run: docker build . --file docker/Dockerfile -t bookappointment:latest 

    - name: Push the image to nexus repo
      run: |
       docker login -u admin -p ${{ secrets.NEXUS_PASSWORD }} http://65.1.134.11:8083
       docker tag bookappointment:latest 65.1.134.11:8083/java-maven-project/bookappointment:v1
       docker push 65.1.134.11:8083/java-maven-project/bookappointment:v1

  deploy:

    runs-on: self-hosted
    
    steps:
    - uses: hashicorp/setup-terraform@v2
      with:
       terraform_version: 1.3.6
    - name: Deploy on Production
      run: |
        cd deploy && terraform init
       # cd deploy/ && terraform apply -auto-approve
       # cd deploy/ && git commit -m 'store terraform state file'
       # cd deploy/ && git push

