name: CI-CD pipeline

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    
   runs-on: self-hosted
   steps:
   - uses: hashicorp/setup-terraform@v2
     with:
      terraform_version: 1.3.6
   - name: Deploy on Production
     run: |
      terraform init
      #cd deploy && terraform init
      #cd deploy/ && terraform apply -auto-approve
      #cd deploy/ && git commit -m 'store terraform state file'
      #cd deploy/ && git push
